#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BaBookApp.Resource", IsApplication=true)]

namespace BaBookApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int AddDateButton = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int AddDescriptionTxt = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int AddLocationTxt = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int AddTitleTxt = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int CommentList_Name = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int CommentList_Text = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int Date = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int Description = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int EventDetail_CommentButton = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int EventDetail_CommentTxt = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int EventDetail_CommentsList = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int EventDetail_Date = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int EventDetail_Desc = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int EventDetail_Group = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int EventDetail_Loc = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int EventDetail_Time = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int EventToolBar = 2131165212;
			
			// aapt resource value: 0x7f070005
			public const int FinalAddEventButton = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int FinallDate = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int FinallDescription = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int FinallLocation = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int FinallTime = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int FinallTitle = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int Location = 2131165210;
			
			// aapt resource value: 0x7f070022
			public const int LoginButton = 2131165218;
			
			// aapt resource value: 0x7f070020
			public const int LoginEmail = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int LoginPassword = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int LoginToolbar = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int MainToolbar = 2131165219;
			
			// aapt resource value: 0x7f07000c
			public const int NewEventDate = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int NewEventDatePick = 2131165193;
			
			// aapt resource value: 0x7f070024
			public const int NewEventTime = 2131165220;
			
			// aapt resource value: 0x7f070017
			public const int Title = 2131165207;
			
			// aapt resource value: 0x7f07001e
			public const int addEventButton = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int listView1 = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int mainFrame = 2131165211;
			
			// aapt resource value: 0x7f070025
			public const int mainmenu_events = 2131165221;
			
			// aapt resource value: 0x7f07000e
			public const int toolbar1 = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEventFinalDialogView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddEventFragmentDialogView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ComentListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DatePicerDialogView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EventDetailMainView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EventListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EventMainView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LoginMainView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MainActivityMainView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TimePicerDialogView = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int BackApiUrl = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
