#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BaBookApp.Resource", IsApplication=true)]

namespace BaBookApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int AddDateButton = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int AddDescriptionTxt = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int AddLocationTxt = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int AddTitleTxt = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int Date = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int Description = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int FinalAddEventButton = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int FinallDate = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int FinallDescription = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int FinallLocation = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int FinallTime = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int FinallTitle = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int Location = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int LoginButton = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int LoginEmail = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int LoginPassword = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int NewEventDate = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int NewEventDatePick = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int NewEventTime = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int Title = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int addEventButton = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int listView1 = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int mainFrame = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int toolbar1 = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEventFinalDialogView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddEventFragmentDialogView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DatePicerDialogView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EventDetailMainView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EventListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EventMainView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoginMainView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TimePicerDialogView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int BackApiUrl = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
