#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BaBookApp.Resource", IsApplication=true)]

namespace BaBookApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int Black = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Grey = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int MainColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SecondMainColor = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int White = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int Big = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ButtonTextSize = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Normal = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EventListSeperator = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EventLIstViewItemBackground = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_add_circle_outline_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_cancel_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_check_circle_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_edit_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_group_add_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_person_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_refresh_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_send_black_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090008
			public const int AddDescriptionTxt = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int AddEvent_AddEventButton = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int AddEvent_CancelButton1 = 2131296266;
			
			// aapt resource value: 0x7f090005
			public const int AddEvent_CancelButton4 = 2131296261;
			
			// aapt resource value: 0x7f09000b
			public const int AddEvent_NextButton1 = 2131296267;
			
			// aapt resource value: 0x7f090013
			public const int AddEvent_NextButton2 = 2131296275;
			
			// aapt resource value: 0x7f090035
			public const int AddEvent_NextButton3 = 2131296309;
			
			// aapt resource value: 0x7f090009
			public const int AddLocationTxt = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int AddTitleTxt = 2131296263;
			
			// aapt resource value: 0x7f090030
			public const int Chat_MessageList = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int Chat_MessageTxt = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int Chat_SendMessageButon = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int Chat_SendMessageButton = 2131296307;
			
			// aapt resource value: 0x7f09002f
			public const int Chat_Toolbar = 2131296303;
			
			// aapt resource value: 0x7f090010
			public const int CommentList_Name = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int CommentList_Text = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int Date = 2131296268;
			
			// aapt resource value: 0x7f090036
			public const int EventDetailMenu_Edit = 2131296310;
			
			// aapt resource value: 0x7f090038
			public const int EventDetailMenu_Invite = 2131296312;
			
			// aapt resource value: 0x7f090037
			public const int EventDetailMenu_Status = 2131296311;
			
			// aapt resource value: 0x7f09001e
			public const int EventDetail_CommentButton = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int EventDetail_CommentTxt = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int EventDetail_CommentsList = 2131296284;
			
			// aapt resource value: 0x7f090019
			public const int EventDetail_Date = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int EventDetail_Date1 = 2131296280;
			
			// aapt resource value: 0x7f090015
			public const int EventDetail_Desc = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int EventDetail_Loc = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int EventDetail_Loc1 = 2131296278;
			
			// aapt resource value: 0x7f09001f
			public const int EventDetail_RefreshButton = 2131296287;
			
			// aapt resource value: 0x7f09001b
			public const int EventDetail_Time = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int EventDetail_Time1 = 2131296282;
			
			// aapt resource value: 0x7f090014
			public const int EventDetail_Toolbar = 2131296276;
			
			// aapt resource value: 0x7f090021
			public const int EventInvite_CancelButton = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int EventInvite_InviteButton = 2131296290;
			
			// aapt resource value: 0x7f090020
			public const int EventInvite_UsersSelection = 2131296288;
			
			// aapt resource value: 0x7f090039
			public const int EventsMenu_AddNewEvent = 2131296313;
			
			// aapt resource value: 0x7f090026
			public const int Events_EventsList = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int Events_Toolbar = 2131296293;
			
			// aapt resource value: 0x7f090003
			public const int FinallDate = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int FinallDescription = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int FinallLocation = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int FinallTime = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int FinallTitle = 2131296256;
			
			// aapt resource value: 0x7f090027
			public const int GroupName = 2131296295;
			
			// aapt resource value: 0x7f090029
			public const int Groups_GroupList = 2131296297;
			
			// aapt resource value: 0x7f090028
			public const int Groups_Toolbar = 2131296296;
			
			// aapt resource value: 0x7f090024
			public const int Location = 2131296292;
			
			// aapt resource value: 0x7f09002d
			public const int LoginButton = 2131296301;
			
			// aapt resource value: 0x7f09002b
			public const int LoginEmail = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int LoginPassword = 2131296300;
			
			// aapt resource value: 0x7f09002a
			public const int LoginToolbar = 2131296298;
			
			// aapt resource value: 0x7f09002e
			public const int MainToolbar = 2131296302;
			
			// aapt resource value: 0x7f09000e
			public const int Message = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int Name = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int NewEventDate = 2131296274;
			
			// aapt resource value: 0x7f090034
			public const int NewEventTime = 2131296308;
			
			// aapt resource value: 0x7f090023
			public const int Title = 2131296291;
			
			// aapt resource value: 0x7f09000d
			public const int UserName = 2131296269;
			
			// aapt resource value: 0x7f09003a
			public const int mainmenu_events = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int mainmenu_groups = 2131296315;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEventFinalDialogView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddEventFragmentDialogView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatListItemView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ComentListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DatePicerDialogView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EventDetailMainView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EventInviteUserDialogView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EventListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EventMainView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int GroupListItemView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int GroupMainView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int InviteListItemView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LoadingScreenView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LoginMainView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MainActivityMainView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int QueueChatMainView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TimePicerDialogView = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int EventDetailMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int EventsMenu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MainMenu = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int BackApiUrl = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int Button = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int DatePicker = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int DialogFragment = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int DialogTitle = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int EditText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int InviteUsers = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int TextEventListItem = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int TextView = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Toolbar = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
